{{- if .Values.application.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
  labels:
  {{- include "prometheusLabel" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames: 
      - {{ .Values.application.name }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  endpoints:
  - port: {{ .Values.application.name }}
    path: /metrics
{{- end }}
